name: app_indexing_b2b_plugin
description: A new flutter plugin project.
version: 0.0.1
author:


environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: io.plugin.app_indexing_b2b_plugin
        pluginClass: AppIndexingB2bPlugin
    